version: "3"

# docker-compose -f docker-compose.yml -f docker-compose.app.yml -p demodev run -d springboot_app

services:
  springboot_app:
    image: demowebos-web:latest
    ports:
      - 8080:8080
      - 8000:8000
    env_file:
      - db.env
    environment:
        # Sfrutta il project name definito esplicitamente
      - DATABASE_HOST=demodev_mysql_db_1
      - DEBUG=true
      - DEBUG_PORT=8000
    # Equivalente dell'opzione "-t" di "docker run"
    tty: true
    # Non in development    
    # restart: always
