version: "3"

# Usa il project name esplicito "demodev" (non devono esserci "_") in modo da avere nomi 
# prevedibili per la network e i container: docker-compose -p demodev up -d

services:
  mysql_db:
    image: mysql
    env_file:
      - db.env
    volumes:
      - ./devscape/mysql/data:/var/lib/mysql
    # Non in development
    # restart: always

  # docker-compose run -d jboss_devstudio

  jboss_devstudio:
    build:
      context: ./dev/jboss_devstudio
      #args:
      #  - usergid
    image: demodev/jboss_devstudio
    volumes:
      # Condivide i sorgenti, la .m2 del container e il workspace dell'IDE
      - .:/home/nomachine/sources
      - ./devscape/maven/.m2:/home/nomachine/.m2
      - ./devscape/jboss_devstudio/workspace:/home/nomachine/devstudio_workspace
      # Condivide il Docker socket
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4001:4000
  
#  mysql_workbench:
#    image: devscape/mysql_workbench:1.0
#    ports:
#      - 4002:4000
