# https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# http://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html

spring:

  # In-memory db H2 in modalita' di compatibilita' MySQL
  datasource:
    platform: h2
    url: jdbc:h2:mem:demowebosh2;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE

  # Usa il dialetto specifico per MySql. Vedi "select @@version;" con la cli di MySql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  # http://localhost:8080/h2-console
  h2:
    console:
      enabled: true

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  test:
    database:
      connection: H2
      replace: ANY

server:
  contextPath: /demowebalone

logging:
  level:
    org:
      hibernate:
        SQL: debug
    it:
      extrasys:
        studio: debug

---

spring:
  profiles: dev
  
  datasource:
    url: jdbc:mysql://localhost:3306/mysqldb
    username: mysql
    password: mysql
    #driver-class-name: com.mysql.jdbc.Driver
  
  jpa:
    #database: MYSQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      # Default to "create-drop" when using an embedded database, "none" otherwise!
      ddl-auto: create-drop

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  test:
    database:
      connection: H2
      replace: ANY

server:
  contextPath: /demowebalone

logging:
  level:
    org:
      hibernate:
        SQL: debug
    it:
      extrasys:
        studio: debug

---
 
spring:
  profiles: dockerdev

  datasource:
    #platform: h2
    #url: jdbc:h2:mem:demowebosh2;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  test:
    database:
      connection: H2
      replace: ANY

server:
  port: 8080
  contextPath: /demowebdock

logging:
  level:
    org:
      hibernate:
        SQL: debug
    it:
      extrasys:
        studio: debug
